apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: techtrends
  strategy: {}
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: techtrends
          ports:
            - containerPort: {{.Values.containerPort}}
          resources:
           {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{.Values.livenessProbe.Path | quote}}
              port: {{ .Values.containerPort }}
          readinessProbe:
            httpGet:
              path: {{.Values.readinessProbe.Path | quote }}
              port: {{ .Values.containerPort }}
status: {}
