apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    tag: {{ .Values.image.tag }}
  name: nginx-alpine
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.services.port }}
    protocol: TCP
    targetPort: {{ .Values.services.port }}
  selector:
    app: nginx
    tag: alpine
  type: {{ .Values.services.type }}
