apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  labels:
    app: techtrends-sandbox
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends-sandbox
  template:
    metadata:
      labels:
        app: techtrends-sandbox
    spec:
      containers:
      - name: techtrends-sandbox
        image: vadlvs/techtrends:latest
        ports:
        - containerPort: 3111
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111