namespace:
  name: demo
 
image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

resources:
  cpu: 50m
  memory: 256Mi

services:
  type: ClusterIP
  port: 8111

configmap:
  data: "version: alpine"

replicaCount: 3