namespace:
  name: sandbox

service:
  port: 4111
  targetPort: {{ .Values.containerPort }}
  protocol: TCP
  type: ClusterIP

image:
  repository: dubiza/techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    memory: 64Mi
    cpu: 250m
  limits:
    memory: 128Mi
    cpu: 500m

containerPort: 3111

livenessProbe:
  httpGet:
    path: /healthz
    port: {{ .Values.containerPort }}
readinessProbe:
  httpGet:
    path: /healthz
    port: {{ .Values.containerPort }}