namespace: prod
service:
  port: 7111
  type: LoadBalancer
replicaCount: 3
image:
  pullPolicy: Always
resources:
  requests:
    memory: "128Mi"
    cpu: "350m"
  limits:
    memory: "256Mi"
    cpu: "500m"
