
name: Kubernetes Artifact Substitue
on:
  workflow_dispatch:
     inputs:
        dockerTag:
          description: 'Docker tag'
          required: true
          default: 'latest'
          type: text
  
jobs:

  update_manifests:
 
    runs-on: "ubuntu-latest"
    steps:
    
     - name: Checkout
       uses: actions/checkout@v3
       
     - name: Substitute artifacts
       uses: Azure/k8s-artifact-substitute@v1
       with:
          # Path to the template manifest files which will be used for deployment.
          # possibly this will be values.yaml for a helm template and we will then bake the helm https://github.com/marketplace/actions/helmfile-render
          manifests: project/kubernetes
          # Fully qualified resource URL of the image(s) to be used for substitutions on the manifest files Example: contosodemo.azurecr.io/helloworld:test
          images: "nadavsinai/techtrends:${{ event.input.dockerTag }}"
        
     - name: Create Pull Request
       uses: peter-evans/create-pull-request@v4
       with:
          token: ${{ secrets.PAT }}
          commit-message: Update deplotment to ${{ event.input.dockerTag }}"
          committer: DeploymentBot <noreply@philips.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: deploy-${{ event.input.dockerTag }}"
          delete-branch: true
          title: '[Deployment] Update version to ${{ event.input.dockerTag }}"'
